# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release Github

on: 
  workflow_dispatch:
    inputs:
      tags:
        type: choice
        description: Make a choice
        options:
          - Alpha
          - Beta
          - Release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10

    - uses: madhead/read-java-properties@latest
      id: mod-version
      with:
        file: gradle.properties
        property: mod_version
        default: 0.0.0

    - run: echo
        
    - name: Create GitHub Release
      uses: KorewaLidesu/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.mod-version.outputs.value }}-${{github.event.inputs.tags}}
        commitish: master
        body: ""
        name:  ${{ github.event.inputs.tags }} ${{ steps.mod-version.outputs.value }}
        prerelease: false
        allow_override: true
        gzip: false
        files: |
            ./artifact/testbridge-${{ steps.mod-version.outputs.value }}.jar
