# Based on https://github.com/CleanroomMC/GroovyScript/blob/63da27acb345aa7af3b8af583cf4c185e0254711/.github/workflows/build.yaml
# This workflow must be manually triggered. It accepts a version and a release type.
# First it sets the version in gradle.properties to the new version and pushes it.
# Then it generates a log, based on commits.
# After that builds a jar and uploads it to curseforge/modrinth/GitHub releases

name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mod version'
        required: true
      tags:
        type: choice
        description: Release tags
        options:
          - alpha
          - beta
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if tag already exists
        run: |
          if git rev-parse --verify --quiet "v${{ github.event.inputs.version }}"; then
            echo "Version ${{ github.event.inputs.version }} already exists, aborting workflow."
            exit 1
          fi

      - name: Set version
        run: sed -i "s/mod_version.*=.*/mod_version = ${{ github.event.inputs.version }}/g" gradle.properties

      - name: Commit and push gradle.properties
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ github.event.inputs.version }}"
          commit_options: "--no-verify"
          file_pattern: gradle.properties
          tagging_message: "v${{ github.event.inputs.version }}"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 719357
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: "v${{ github.event.inputs.version }}-${{ github.event.inputs.tags }}"
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
          name: TestBridge-${{ github.event.inputs.version }}
          version: ${{ github.event.inputs.version }}
          version-type: ${{ github.event.inputs.tags }}
          loaders: |
            forge
          game-versions: |
            1.12.2
          dependencies: |
            logistics-pipes | depends | *
            mixin-booter | depends | *
            ae2-extended-life | recommends | *
            logistics-bridge | breaks | *
            logistics-bridge-dmnedition | breaks | *
          java: |
            8
          retry-attempts: 2

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/*.jar
